In [119]:
import pandas as pd
comments=pd.read_csv('comments_original.csv')

In [126]:
movies=pd.read_csv('movie-1.1.csv')

In [127]:
comments

,productId,userId,profileName,helpfulness,score,time,summary,text
0,B003AI2VGA,A141HP4LYPWMSR,"Brian E. Erland ""Rainbow Sphinx""",7/7,3.0,1182729600,"""There Is So Much Darkness Now ~ Come For The ...","Synopsis: On the daily trek from Juarez, Mexic..."
1,B003AI2VGA,A328S9RN3U5M68,Grady Harp,4/4,3.0,1181952000,Worthwhile and Important Story Hampered by Poo...,THE VIRGIN OF JUAREZ is based on true events s...
2,B003AI2VGA,A1I7QGUDP043DG,"Chrissy K. McVay ""Writer""",8/10,5.0,1164844800,This movie needed to be made.,The scenes in this film can be very disquietin...
3,B003AI2VGA,A1M5405JH9THP9,golgotha.gov,1/1,3.0,1197158400,distantly based on a real tragedy,THE VIRGIN OF JUAREZ (2006)<br />directed by K...
4,B003AI2VGA,ATXL536YX71TR,"KerrLines ""&#34;Movies,Music,Theatre&#34;""",1/1,3.0,1188345600,"""What's going on down in Juarez and shining a ...","Informationally, this SHOWTIME original is ess..."
...,...,...,...,...,...,...,...,...
7911679,B003A3PGF8,A11H5P3Z6WGN8G,Peter J. Scardino,1/2,3.0,1262995200,Long Live The Queen review,I was a little disappointed in Lisa Lampannell...
7911680,B003A3PGF8,A7QMQBGJ2TCQG,Paul Garland,0/1,5.0,1241308800,Lisa Lampanelli,"Lisa Lampanelli is crude, cusses like a sailor..."
7911681,6304952198,AT0A56QQS6PKO,Madge Leek,7/7,2.0,1180828800,Hollow earth theory? Interesting...Hollow eart...,"As a listener to C2C, I was excited about this..."
7911682,6304952198,A23KKLV2CD39U8,"James Newman ""Dark Lord""",0/0,4.0,1268265600,the Hollow earth,"This was a very interesting dvd, but the let d..."
7911683,6304952198,AIW7RUV8P2FK1,Eddie Van Ryan,5/13,5.0,1141776000,The Earth is Hollow!,"Now for the first time, this film presents the..."

In [128]:
movies

,Title,Release date,Directors,Actors,Genres,Asin
0,- Learn To Sing Gospel,"February 1, 2007","Greg Hannon, M.M.","Canagela Robertson,M.m.",NaN,B000O1OWQS
1,- Learning To Flatpick,"June 3, 2003","Traum, Happy","Kaufman,Steve",NaN,B000092OM6
2,100 Boating Mistakes & How To Avoid Them Trai...,"January 1, 2007",NaN,NaN,NaN,B0004ILML4
3,100 Sailing Mistakes & How To Avoid Them Trai...,"January 1, 2007",NaN,NaN,NaN,B0004IXFE6
4,100 Saltwater Fishing Mistakes & How To Avoid...,"January 1, 2007",NaN,NaN,NaN,B0004ILMKA
...,...,...,...,...,...,...
152466,Águila o sol,"June 30, 1996",Arcady Boytler,"Cantinflas,Manuel Medel,Margarita Mora,Marina ...",NaN,6302296285
152467,Æon Flux,"June 3, 2008",Karyn Kusama,"Charlize Theron,Frances Mcdormand,Sophie Okone...",NaN,B000IOM0WE
152468,ÇA TWISTE À POPONGUINE (Rocking Poponguine),"September 10, 2009",Moussa Sene Absa,"Coura Ba,Jean-françois Balmer,Ousmane Bo",Arthouse,"B002SUHWDI,B002SUDU48"
152469,Ça commence aujourd'hui,"January 21, 2003",Bertrand Tavernier,"Philippe Torreton,Maria Pitarresi,Nadia Kaci,V...",NaN,"B00004VYF2,B00004D2WE"
152470,Ôdishon,"March 20, 2002",Takashi Miike,"Ryo Ishibashi,Eihi Shiina,Tetsu Sawaki,Jun Kun...",NaN,"B00005MKXB,B00005MKXA"

In [7]:
asin1='B002ITUV3M'
c1=comments[comments['productId']==asin1]
asin2='B002ITQZZU'
c2=comments[comments['productId']==asin2]
pd.concat([c1,c2])

,productId,userId,profileName,helpfulness,score,time,summary,text
5404842,B002ITUV3M,A39RQCXD82ZXA7,"michael oconnell ""michael""",0/0,5.0,1301097600,Amazing new information!,Incredible spoof on the inept attempts by gove...
5404843,B002ITUV3M,A2NS9Q98DI6D2X,"F. Sinclair ""Knowledge Seeker""",0/1,1.0,1244332800,"""C"" Grade Made Movie.",This is an absolute 3nd rate movie and even th...
5404844,B002ITUV3M,A2PMU6IJ3LLT4T,"C. Oconnell ""artunemedia""",0/2,5.0,1237939200,amazing revelations,We are priveleged to present a film that revea...
5613560,B002ITQZZU,A39RQCXD82ZXA7,"michael oconnell ""michael""",0/0,5.0,1301097600,Amazing new information!,Incredible spoof on the inept attempts by gove...
5613561,B002ITQZZU,A2NS9Q98DI6D2X,"F. Sinclair ""Knowledge Seeker""",0/1,1.0,1244332800,"""C"" Grade Made Movie.",This is an absolute 3nd rate movie and even th...
5613562,B002ITQZZU,A2PMU6IJ3LLT4T,"C. Oconnell ""artunemedia""",0/2,5.0,1237939200,amazing revelations,We are priveleged to present a film that revea...

In [29]:
for i,r in pd.concat([comments[comments['productId']==a] for a in 'B002ITUV3M,B002ITQZZU,B001T4Y17E'.split(',')]).iterrows():
    print('movie' in r['text'])

False
True
False
False
True
False
False
True
False

In [17]:
movies.columns.values

array(['Title', 'Release date', 'Directors', 'Actors', 'Genres', 'Asin'],
      dtype=object)

In [121]:
# 先提取movie id
movie_id=set()
count=0
for index,row in comments.iterrows():
    count+=1
    if count%10000==0:
        print(count,end=' ')
    if 'movie' in row['text'] or 'film' in row['text']:
        movie_id.add(str(row['productId']))

10000 20000 30000 40000 50000 60000 70000 80000 90000 100000 110000 120000 130000 140000 150000 160000 170000 180000 190000 200000 210000 220000 230000 240000 250000 260000 270000 280000 290000 300000 310000 320000 330000 340000 350000 360000 370000 380000 390000 400000 410000 420000 430000 440000 450000 460000 470000 480000 490000 500000 510000 520000 530000 540000 550000 560000 570000 580000 590000 600000 610000 620000 630000 640000 650000 660000 670000 680000 690000 700000 710000 720000 730000 740000 750000 760000 770000 780000 790000 800000 810000 820000 830000 840000 850000 860000 870000 880000 890000 900000 910000 920000 930000 940000 950000 960000 970000 980000 990000 1000000 1010000 1020000 1030000 1040000 1050000 1060000 1070000 1080000 1090000 1100000 1110000 1120000 1130000 1140000 1150000 1160000 1170000 1180000 1190000 1200000 1210000 1220000 1230000 1240000 1250000 1260000 1270000 1280000 1290000 1300000 1310000 1320000 1330000 1340000 1350000 1360000 1370000 1380000 1390000 1400000 1410000 1420000 1430000 1440000 1450000 1460000 1470000 1480000 1490000 1500000 1510000 1520000 1530000 1540000 1550000 1560000 1570000 1580000 1590000 1600000 1610000 1620000 1630000 1640000 1650000 1660000 1670000 1680000 1690000 1700000 1710000 1720000 1730000 1740000 1750000 1760000 1770000 1780000 1790000 1800000 1810000 1820000 1830000 1840000 1850000 1860000 1870000 1880000 1890000 1900000 1910000 1920000 1930000 1940000 1950000 1960000 1970000 1980000 1990000 2000000 2010000 2020000 2030000 2040000 2050000 2060000 2070000 2080000 2090000 2100000 2110000 2120000 2130000 2140000 2150000 2160000 2170000 2180000 2190000 2200000 2210000 2220000 2230000 2240000 2250000 2260000 2270000 2280000 2290000 2300000 2310000 2320000 2330000 2340000 2350000 2360000 2370000 2380000 2390000 2400000 2410000 2420000 2430000 2440000 2450000 2460000 2470000 2480000 2490000 2500000 2510000 2520000 2530000 2540000 2550000 2560000 2570000 2580000 2590000 2600000 2610000 2620000 2630000 2640000 2650000 2660000 2670000 2680000 2690000 2700000 2710000 2720000 2730000 2740000 2750000 2760000 2770000 2780000 2790000 2800000 2810000 2820000 2830000 2840000 2850000 2860000 2870000 2880000 2890000 2900000 2910000 2920000 2930000 2940000 2950000 2960000 2970000 2980000 2990000 3000000 3010000 3020000 3030000 3040000 3050000 3060000 3070000 3080000 3090000 3100000 3110000 3120000 3130000 3140000 3150000 3160000 3170000 3180000 3190000 3200000 3210000 3220000 3230000 3240000 3250000 3260000 3270000 3280000 3290000 3300000 3310000 3320000 3330000 3340000 3350000 3360000 3370000 3380000 3390000 3400000 3410000 3420000 3430000 3440000 3450000 3460000 3470000 3480000 3490000 3500000 3510000 3520000 3530000 3540000 3550000 3560000 3570000 3580000 3590000 3600000 3610000 3620000 3630000 3640000 3650000 3660000 3670000 3680000 3690000 3700000 3710000 3720000 3730000 3740000 3750000 3760000 3770000 3780000 3790000 3800000 3810000 3820000 3830000 3840000 3850000 3860000 3870000 3880000 3890000 3900000 3910000 3920000 3930000 3940000 3950000 3960000 3970000 3980000 3990000 4000000 4010000 4020000 4030000 4040000 4050000 4060000 4070000 4080000 4090000 4100000 4110000 4120000 4130000 4140000 4150000 4160000 4170000 4180000 4190000 4200000 4210000 4220000 4230000 4240000 4250000 4260000 4270000 4280000 4290000 4300000 4310000 4320000 4330000 4340000 4350000 4360000 4370000 4380000 4390000 4400000 4410000 4420000 4430000 4440000 4450000 4460000 4470000 4480000 4490000 4500000 4510000 4520000 4530000 4540000 4550000 4560000 4570000 4580000 4590000 4600000 4610000 4620000 4630000 4640000 4650000 4660000 4670000 4680000 4690000 4700000 4710000 4720000 4730000 4740000 4750000 4760000 4770000 4780000 4790000 4800000 4810000 4820000 4830000 4840000 4850000 4860000 4870000 4880000 4890000 4900000 4910000 4920000 4930000 4940000 4950000 4960000 4970000 4980000 4990000 5000000 5010000 5020000 5030000 5040000 5050000 5060000 5070000 5080000 5090000 5100000 5110000 5120000 5130000 5140000 5150000 5160000 5170000 5180000 5190000 5200000 5210000 5220000 5230000 5240000 5250000 5260000 5270000 5280000 5290000 5300000 5310000 5320000 5330000 5340000 5350000 5360000 5370000 5380000 5390000 5400000 5410000 5420000 5430000 5440000 5450000 5460000 5470000 5480000 5490000 5500000 5510000 5520000 5530000 5540000 5550000 5560000 5570000 5580000 5590000 5600000 5610000 5620000 5630000 5640000 5650000 5660000 5670000 5680000 5690000 5700000 5710000 5720000 5730000 5740000 5750000 5760000 5770000 5780000 5790000 5800000 5810000 5820000 5830000 5840000 5850000 5860000 5870000 5880000 5890000 5900000 5910000 5920000 5930000 5940000 5950000 5960000 5970000 5980000 5990000 6000000 6010000 6020000 6030000 6040000 6050000 6060000 6070000 6080000 6090000 6100000 6110000 6120000 6130000 6140000 6150000 6160000 6170000 6180000 6190000 6200000 6210000 6220000 6230000 6240000 6250000 6260000 6270000 6280000 6290000 6300000 6310000 6320000 6330000 6340000 6350000 6360000 6370000 6380000 6390000 6400000 6410000 6420000 6430000 6440000 6450000 6460000 6470000 6480000 6490000 6500000 6510000 6520000 6530000 6540000 6550000 6560000 6570000 6580000 6590000 6600000 6610000 6620000 6630000 6640000 6650000 6660000 6670000 6680000 6690000 6700000 6710000 6720000 6730000 6740000 6750000 6760000 6770000 6780000 6790000 6800000 6810000 6820000 6830000 6840000 6850000 6860000 6870000 6880000 6890000 6900000 6910000 6920000 6930000 6940000 6950000 6960000 6970000 6980000 6990000 7000000 7010000 7020000 7030000 7040000 7050000 7060000 7070000 7080000 7090000 7100000 7110000 7120000 7130000 7140000 7150000 7160000 7170000 7180000 7190000 7200000 7210000 7220000 7230000 7240000 7250000 7260000 7270000 7280000 7290000 7300000 7310000 7320000 7330000 7340000 7350000 7360000 7370000 7380000 7390000 7400000 7410000 7420000 7430000 7440000 7450000 7460000 7470000 7480000 7490000 7500000 7510000 7520000 7530000 7540000 7550000 7560000 7570000 7580000 7590000 7600000 7610000 7620000 7630000 7640000 7650000 7660000 7670000 7680000 7690000 7700000 7710000 7720000 7730000 7740000 7750000 7760000 7770000 7780000 7790000 7800000 7810000 7820000 7830000 7840000 7850000 7860000 7870000 7880000 7890000 7900000 7910000

In [129]:
len(movie_id)

190356

In [98]:
movie_id_df=pd.DataFrame(data={'id':list(movie_id)})

In [102]:
movie_id_df.to_csv('movie_id.csv',index=False,sep=',')

In [106]:
# new_movies=pd.DataFrame(columns=['Title', 'Release date', 'Directors', 'Actors', 'Genres', 'Asin','Score','Edition'])

In [104]:
# 去除非电影
# import warnings
# warnings.filterwarnings('ignore') # setting ignore as a parameter

# count=0
# for index,row in movies.iterrows():
#     count+=1
#     if count%1000 == 0:
#         print(count,end=' ')
# #     for i,r in pd.concat([comments[comments['productId']==a] for a in str(row['Asin']).split(',')]).iterrows():
# #         if 'movie' in r['text'] or 'film' in r['text']:
# #             new_movies=new_movies.append(row)
# #             break
#     for a in str(row['Asin']).split(','):
#         if a in movie_id:
#             new_movies=new_movies.append(row)
#             break

1000 2000 3000 4000 5000 6000 7000 8000 9000 10000 11000 12000 13000 14000 15000 16000 17000 18000 19000 20000 21000 22000 23000 24000 25000 26000 27000 28000 29000 30000 31000 32000 33000 34000 35000 36000 37000 38000 39000 40000 41000 42000 43000 44000 45000 46000 47000 48000 49000

KeyboardInterrupt:

In [130]:
def filter_movie(asin_str:str):
    for a in asin_str.split(','):
        if a in movie_id:
            return True
    return False

In [132]:
new_movies = movies[movies['Asin'].map(filter_movie)]

In [133]:
new_movies

,Title,Release date,Directors,Actors,Genres,Asin
3,100 Sailing Mistakes & How To Avoid Them Trai...,"January 1, 2007",NaN,NaN,NaN,B0004IXFE6
7,Dance Pack: Saturday Night Fever / Footloose ...,"September 25, 2005",NaN,NaN,NaN,B00065GX7I
9,Double Feature: Young Land / Ghost Train (sl...,"November 03, 2009","Ted Tetzlaff, Ted Nicolau","Dennis Hopper,Terence Hill,Yvonne Craig,Jack E...",NaN,B000XSBE54
15,For Cats: While You Are Gone Relaxing Cat Vid...,"October 15, 2007",Pet Music Artists,"Cats,Birds,Fish,Etc.",NaN,B000XC0E6K
29,Little Dorrit: Nobody's Fault and Little Dorr...,"December 10, 1999",Christine Edzard,"Derek Jacobi,Alec Guinness,Joan Greenwood,Max ...",NaN,B00004CL40
...,...,...,...,...,...,...
152466,Águila o sol,"June 30, 1996",Arcady Boytler,"Cantinflas,Manuel Medel,Margarita Mora,Marina ...",NaN,6302296285
152467,Æon Flux,"June 3, 2008",Karyn Kusama,"Charlize Theron,Frances Mcdormand,Sophie Okone...",NaN,B000IOM0WE
152468,ÇA TWISTE À POPONGUINE (Rocking Poponguine),"September 10, 2009",Moussa Sene Absa,"Coura Ba,Jean-françois Balmer,Ousmane Bo",Arthouse,"B002SUHWDI,B002SUDU48"
152469,Ça commence aujourd'hui,"January 21, 2003",Bertrand Tavernier,"Philippe Torreton,Maria Pitarresi,Nadia Kaci,V...",NaN,"B00004VYF2,B00004D2WE"
152470,Ôdishon,"March 20, 2002",Takashi Miike,"Ryo Ishibashi,Eihi Shiina,Tetsu Sawaki,Jun Kun...",NaN,"B00005MKXB,B00005MKXA"

In [134]:
new_movies.to_csv('movie-1.2.csv',index=False,sep=',')