In [1]:
import pandas as pd

In [2]:
movies=pd.read_csv('movie-2.2.csv')

In [3]:
movies

,Title,Release date,Directors,Actors,Genres,Asin,Score,Edition,Format,ID
0,100 Sailing Mistakes & How To Avoid Them Trai...,"January 1, 2007",NaN,NaN,Special Interests,B0004IXFE6,2.666667,1,"NTSC, DVD,Color",0
1,Dance Pack: Saturday Night Fever / Footloose ...,"September 25, 2005",NaN,NaN,Drama,B00065GX7I,4.500000,1,NaN,1
2,Double Feature: Young Land / Ghost Train,"November 03, 2009","Ted Nicolau,Ted Tetzlaff","Dennis Hopper,Patrick Wayne,Terence Hill,Yvonn...",Westerns,B000XSBE54,4.000000,1,"NTSC,Color, Full Screen, HiFi Sound, Mono",2
3,For Cats: While You Are Gone Relaxing Cat Vid...,"October 15, 2007",Pet Music Artists,"Cats,Fish,Birds,Etc.",Special Interests,B000XC0E6K,3.597015,1,NTSC,3
4,Little Dorrit: Nobody'S Fault And Little Dorr...,"December 10, 1999",Christine Edzard,"Derek Jacobi,Max Wall,Alec Guinness,Joan Green...",Drama,B00004CL40,3.285714,1,NaN,4
...,...,...,...,...,...,...,...,...,...,...
83915,Águila O Sol,"June 30, 1996",Arcady Boytler,"Margarita Mora,Manuel Medel,Luis G. Barreiro,C...",Mexico,6302296285,2.000000,1,NaN,83915
83916,Æon Flux,"June 3, 2008",Karyn Kusama,"Marton Csokas,Frances Mcdormand,Sophie Okonedo...",Movies,B000IOM0WE,3.405512,1,"NTSC,Multiple Formats, Dolby, Blu-ray, Subtit...",83916
83917,Ça Commence Aujourd'Hui,"January 21, 2003",Bertrand Tavernier,"Nadia Kaci,Véronique Ataly,Philippe Torreton,N...",French,"B00004D2WE,B00004VYF2",5.000000,2,PAL,83917
83918,Ça Twiste À Poponguine,"September 10, 2009",Moussa Sene Absa,"Ousmane Bo,Coura Ba,Jean-françois Balmer",Arthouse,"B002SUDU48,B002SUHWDI",2.500000,2,Available to watch on,83918
83919,Ôdishon,"March 20, 2002",Takashi Miike,"Renji Ishibashi,Tetsu Sawaki,Ryo Ishibashi,Eih...",Japanese,"B00005MKXA,B00005MKXB",3.886640,2,PAL,83919

In [4]:
Genre=pd.DataFrame(columns=['genre_id','genre_name','movie_id','movie_title'])

In [5]:
import gc

count=0
for i,r in movies.iterrows():
    if not pd.isna(r['Genres']):
        Genre=pd.concat([Genre,pd.DataFrame(data={'genre_name':[r['Genres']],'movie_id':[r['ID']],'movie_title':[r['Title']]})],ignore_index=True)
        
    count+=1
    if count%1000==0:
        print(count,end=' ')
        gc.collect()

1000 2000 3000 4000 5000 6000 7000 8000 9000 10000 11000 12000 13000 14000 15000 16000 17000 18000 19000 20000 21000 22000 23000 24000 25000 26000 27000 28000 29000 30000 31000 32000 33000 34000 35000 36000 37000 38000 39000 40000 41000 42000 43000 44000 45000 46000 47000 48000 49000 50000 51000 52000 53000 54000 55000 56000 57000 58000 59000 60000 61000 62000 63000 64000 65000 66000 67000 68000 69000 70000 71000 72000 73000 74000 75000 76000 77000 78000 79000 80000 81000 82000 83000

In [7]:
Genre

,genre_id,genre_name,movie_id,movie_title
0,NaN,Special Interests,0,100 Sailing Mistakes & How To Avoid Them Trai...
1,NaN,Drama,1,Dance Pack: Saturday Night Fever / Footloose ...
2,NaN,Westerns,2,Double Feature: Young Land / Ghost Train
3,NaN,Special Interests,3,For Cats: While You Are Gone Relaxing Cat Vid...
4,NaN,Drama,4,Little Dorrit: Nobody'S Fault And Little Dorr...
...,...,...,...,...
83907,NaN,Mexico,83915,Águila O Sol
83908,NaN,Movies,83916,Æon Flux
83909,NaN,French,83917,Ça Commence Aujourd'Hui
83910,NaN,Arthouse,83918,Ça Twiste À Poponguine
83911,NaN,Japanese,83919,Ôdishon

In [8]:
Genre['genre_id']=Genre.index

In [9]:
Genre

,genre_id,genre_name,movie_id,movie_title
0,0,Special Interests,0,100 Sailing Mistakes & How To Avoid Them Trai...
1,1,Drama,1,Dance Pack: Saturday Night Fever / Footloose ...
2,2,Westerns,2,Double Feature: Young Land / Ghost Train
3,3,Special Interests,3,For Cats: While You Are Gone Relaxing Cat Vid...
4,4,Drama,4,Little Dorrit: Nobody'S Fault And Little Dorr...
...,...,...,...,...
83907,83907,Mexico,83915,Águila O Sol
83908,83908,Movies,83916,Æon Flux
83909,83909,French,83917,Ça Commence Aujourd'Hui
83910,83910,Arthouse,83918,Ça Twiste À Poponguine
83911,83911,Japanese,83919,Ôdishon

In [10]:
Genre.to_csv('sql-data/Genre.csv',index=False)